### ISSUE TITLE
Meaning of columns in .tsv files

### ISSUE THREAD

**Issue by sean-la** [NCBI-Hackathons/Virus_Detection_SRA#10]
I was just wondering what the precise definitions of the columns `avgMAPQ`, `avgScore` and `avgEditDist` are in the `.tsv` files. Thanks!

**Comment by pcantalupo** [comment]
The avg (average) fields are the average MAPQ (or Score or Editdist) across the alignments for each subject in the BAM file. MAPQ, Score and EditDist are taken from field 5, the AS flag, and the NM flag in the BAM file, respectively.

Added this documentation to README.md
https://github.com/NCBI-Hackathons/Virus_Detection_SRA/commit/2d9836c4dd8c2bce5c815ec1a5e1d1d1b655fec1
