### ISSUE TITLE
Possible to get taxonomic family for each matching virus?

### ISSUE THREAD

**Issue by sean-la** [NCBI-Hackathons/Virus_Detection_SRA#11]
Is it possible to modify SIDEARM so that the `.tsv` files contain the taxonomic family for each matching virus?

**Comment by pcantalupo** [comment]
Yes that can be done but need somebody to write the code. Are you volunteering to do it? :)

You could do it by either 1) creating a local installation of the NCBI taxonomy database and then look up information in there or 2) use Eutils to query NCBI.

**Comment by sean-la** [comment]
Haha, I think modifying SIDEARM to also output the family for each virus is something I could do in the future.

**Comment by neksa** [comment]
Ideally it could be implemented as an additional workflow step with a wrapper around the taxonomy tool as Paul described. This step could just add an extra column to the tab file.
